language: php
matrix:
  include:
    - php: 5.4
      env: PUG_VERSION='2.7.1'
    - php: 5.5
      env: PUG_VERSION='2.7.1'
    - php: 5.5
      env: PUG_VERSION='^3.0@alpha'
    - php: 5.6
      env: PUG_VERSION='2.7.1'
    - php: 5.6
      env: PUG_VERSION='^3.0@alpha'
    - php: 7.0
      env: PUG_VERSION='2.7.1'
    - php: 7.0
      env: PUG_VERSION='^3.0@alpha'
    - php: 7.1
      env: PUG_VERSION='2.7.1'
    - php: 7.1
      env: PUG_VERSION='^3.0@alpha'
    - php: 7.2
      env: PUG_VERSION='2.7.1'
    - php: 7.2
      env: PUG_VERSION='^3.0@alpha'
    - php: hhvm
      env: PUG_VERSION='2.7.1'
      dist: trusty
      sudo: required
    - php: hhvm
      env: PUG_VERSION='^3.0@alpha'
      dist: trusty
      sudo: required
before_script:
  - travis_retry composer self-update
  - if [ "$PUG_VERSION" != "" ]; then travis_retry composer require "pug-php/pug:${PUG_VERSION}" --no-update; fi;
  - travis_retry composer update --no-interaction
script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml
after_script:
  - vendor/bin/test-reporter --coverage-report coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  code_climate:
    repo_token: 25328431329b40920e6ddb0ef51ec0bb863500568db2467e9abcff726347e29e
